# Generated by Django 5.1.6 on 2025-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
