# Generated by Django 5.1.6 on 2025-03-16 19:18

import apps.accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_restaurant_qrcodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='qrCodeID',
            field=models.CharField(default=apps.accounts.utils.generate_unique_qr_code, max_length=16, unique=True),
        ),
    ]
