# Generated by Django 5.1.6 on 2025-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_restaurant_qrcodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemimage',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
