# Generated by Django 5.1.6 on 2025-03-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_items_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
            options={
                'unique_together': {('account', 'restaurant', 'check_in_date')},
            },
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
