# Generated by Django 5.1.6 on 2025-03-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurant_points_usercheckin_delete_checkin'),
    ]

    #operations = [
        #migrations.DeleteModel(
            #name='CheckIn',
        #),
    #]
