# Generated by Django 5.1.6 on 2025-03-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_total_points'),
        ('accounts', '0005_restaurant_points_usercheckin_delete_checkin'),
    ]

    operations = [
    ]
