# Generated by Django 5.1.6 on 2025-02-24 17:14

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_account_avatar_account_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="items",
            fields=[
                ("itemid", models.AutoField(primary_key=True, serialize=False)),
                ("itemName", models.CharField(default="", max_length=100)),
                ("itemCost", models.IntegerField(default=20)),
                (
                    "itemimage",
                    models.CharField(default="put/root/here", max_length=500),
                ),
                ("itemslot", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="bio",
            field=encrypted_model_fields.fields.EncryptedCharField(default=" "),
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.items"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
