# Generated by Django 5.1.6 on 2025-03-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_checkin'),
    ]

    #operations = [
    #   migrations.DeleteModel(
    #      name='CheckIn',
    # ),
    #]
