# Generated by Django 5.1.5 on 2025-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_bio'),
        ('accounts', '0008_rename_itemid_purchases_item_purchases_equipstate_and_more'),
    ]

    operations = [
    ]
