# Generated by Django 5.1.5 on 2025-02-27 11:55

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250227_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.items'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
