# Generated by Django 5.1.6 on 2025-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_badge_alter_account_avatar_alter_account_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="itemimage",
            field=models.ImageField(upload_to="items/"),
        ),
    ]
