# Generated by Django 5.1.5 on 2025-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurant_qrcodeid_alter_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='qrCodeID',
            field=models.CharField(default='generate_unique_qr_code', max_length=16, unique=True),
        ),
    ]
