# Generated by Django 5.1.5 on 2025-03-12 11:14

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20250312_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='link',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qrCodeID',
            field=models.CharField(default=accounts.utils.generate_unique_qr_code, max_length=16, unique=True),
        ),
    ]
