# Stage 1: Build Dependencies
FROM python:3.11-slim as builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Runtime Image
FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY manage.py /app/
COPY config/ /app/config/
COPY apps/accounts/ /app/accounts/
COPY apps/qr_scanner/ /app/qr_scanner/
COPY apps/quiz/ /app/quiz/

# Create necessary directories
RUN mkdir -p /app/staticfiles
RUN mkdir -p /app/media

# Create a non-root user
RUN adduser --system --group django

# Set permissions for static and media files
RUN chown -R django:django /app/staticfiles /app/media

# Switch to the non-root user
USER django

EXPOSE 8000

# Healthcheck to ensure the service is running
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl --fail http://0.0.0.0:8000/ || exit 1

# Command to run the application
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]