FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ensure the static directory exists
RUN mkdir -p /app/static

# Ensure the STATIC_ROOT directory exists
RUN mkdir -p /app/staticfiles

# Debugging steps
RUN echo "Current directory:" && pwd
RUN echo "Contents of /app:" && ls -la /app

# Collect static files
RUN python manage.py collectstatic --noinput  # Ensure this line is present

CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
