# Generated by Django 5.1.5 on 2025-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('accoutnType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('taskID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
