# Generated by Django 5.1.5 on 2025-02-24 23:18

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=encrypted_model_fields.fields.EncryptedCharField(default=' '),
        ),
    ]
