# Generated by Django 5.1.6 on 2025-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_items_alter_account_bio_purchases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchases",
            old_name="itemid",
            new_name="item",
        ),
        migrations.AddField(
            model_name="purchases",
            name="equipState",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="items",
            name="itemimage",
            field=models.CharField(default="ItemImage", max_length=500),
        ),
    ]
