# Generated by Django 5.1.5 on 2025-03-10 18:21

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_purchases_item_alter_purchases_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qrCodeID',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
    ]
