# Generated by Django 5.1.6 on 2025-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_purchases_item_alter_purchases_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
