# Generated by Django 5.1.5 on 2025-03-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurant_link'),
        ('accounts', '0012_alter_restaurant_qrcodeid'),
    ]

    operations = [
    ]
